## Values for the external vSphere Cloud Provider
# external_vsphere_vcenter_ip: "myvcenter.domain.com"
# external_vsphere_vcenter_port: "443"
# external_vsphere_insecure: "true"
# external_vsphere_user: "administrator@vsphere.local"
# external_vsphere_password: "K8s_admin"
# external_vsphere_datacenter: "DATACENTER_name"
# external_vsphere_kubernetes_cluster_id: "kubernetes-cluster-id"

## Tags for the external vSphere Cloud Provider images
# external_vsphere_cloud_controller_image_tag: "latest"
# external_vsphere_syncer_image_tag: "v1.0.2"
# external_vsphere_csi_attacher_image_tag: "v1.1.1"
# external_vsphere_csi_controller: "v1.0.2"
# external_vsphere_csi_liveness_probe_image_tag: "v1.1.0"
# external_vsphere_csi_provisioner_image_tag: "v1.2.2"
